[build]
commands = [
  "pip install -r requirements.txt",
  "python manage.py migrate",
  "npm ci --cache .npm --prefer-offline",
  "npm run build",
  "cp -r build/* staticfiles/",
  "python manage.py collectstatic --noinput --clear"
]

[deploy]
startCommand = "gunicorn almostme.wsgi:application --bind 0.0.0.0:$PORT"
