# Generated by Django 4.2.7 on 2025-09-07 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('warmup_exercises', models.JSONField(blank=True, default=list)),
                ('exercises', models.JSONField(blank=True, default=list)),
                ('suitable_for_injuries', models.JSONField(blank=True, default=list)),
                ('suitable_for_pregnant', models.BooleanField(default=False)),
                ('goal', models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='maintenance', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.FloatField(help_text='Weight in kilograms')),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('age', models.PositiveIntegerField()),
                ('goal', models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='maintenance', max_length=20)),
                ('injury', models.CharField(blank=True, help_text='Physical injury or condition', max_length=100, null=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
